# Setup
title: Xu Liu (Lexi)
description: M.Phil. in Risk Management Science (Expected 2023), CUHK
url: https://lexilxu.github.io/MyPage/
avatar: /profile.JPG
paginate: 5
permalink:  pretty
cover_image: bluebg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

sass:
  sass_dir: _sass
  style: :compressed
  
author:
  name: Xu Liu
  url: https://lexiliu392.github.io/lexilxu/
  email: lexilxu@gmail.com
