# Setup
title: Xu Liu (Lexi)
description: MPhil in Risk Management Science (Expected 2023), CUHK
url: https://lexiliu392.github.io/lexilxu/
avatar: /profile.JPG
# paginate: 5
permalink: /index/
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
